[2024-04-09T19:51:54.246+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-09T19:51:54.579+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fruits_dag.insert_fruit_data manual__2024-04-09T19:42:16.415292+00:00 [queued]>
[2024-04-09T19:51:54.737+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fruits_dag.insert_fruit_data manual__2024-04-09T19:42:16.415292+00:00 [queued]>
[2024-04-09T19:51:54.742+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-09T19:51:54.930+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): insert_fruit_data> on 2024-04-09 19:42:16.415292+00:00
[2024-04-09T19:51:55.000+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=292) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-09T19:51:55.005+0000] {standard_task_runner.py:63} INFO - Started process 319 to run task
[2024-04-09T19:51:55.112+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fruits_dag', 'insert_fruit_data', 'manual__2024-04-09T19:42:16.415292+00:00', '--job-id', '449', '--raw', '--subdir', 'DAGS_FOLDER/fruit_table_dag.py', '--cfg-path', '/tmp/tmpm7sz9i1v']
[2024-04-09T19:51:55.150+0000] {standard_task_runner.py:91} INFO - Job 449: Subtask insert_fruit_data
[2024-04-09T19:51:55.779+0000] {task_command.py:426} INFO - Running <TaskInstance: fruits_dag.insert_fruit_data manual__2024-04-09T19:42:16.415292+00:00 [running]> on host a89a4f7de6ef
[2024-04-09T19:51:56.418+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fruits_dag' AIRFLOW_CTX_TASK_ID='insert_fruit_data' AIRFLOW_CTX_EXECUTION_DATE='2024-04-09T19:42:16.415292+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-09T19:42:16.415292+00:00'
[2024-04-09T19:51:56.424+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-09T19:51:56.476+0000] {base.py:84} INFO - Using connection ID 'eksplorasi_postgres' for task execution.
[2024-04-09T19:51:56.841+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-09T19:51:56.861+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/fruit_table_dag.py", line 21, in insert_fruit_data_into_db
    fruit['name'],
    ~~~~~^^^^^^^^
TypeError: string indices must be integers, not 'str'
[2024-04-09T19:51:57.055+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=fruits_dag, task_id=insert_fruit_data, execution_date=20240409T194216, start_date=20240409T195154, end_date=20240409T195157
[2024-04-09T19:51:57.257+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 449 for task insert_fruit_data (string indices must be integers, not 'str'; 319)
[2024-04-09T19:51:57.443+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-09T19:51:57.747+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-09T19:51:57.794+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
